# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-RuledValidator-Plugin-Japanese
version:      0.01
version_from: lib/Data/RuledValidator/Plugin/Japanese.pm
installdirs:  site
requires:
    Data::FormValidator::Constraints::Japanese: 0.04
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
